# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugijjns may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-vi-mode history-substring-search zsh-autosuggestions copydir dirhistory zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"#


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

if [ -f ~/.zshrc_aliases_tc_imported_by_zshrc ]; then
    . ~/.zshrc_aliases_tc_imported_by_zshrc
fi

#overrider ctrl+c to ctrl+x
stty intr "^x"


#export PATH=$PATH:/opt/pycharm-2024.1.2/bin/pycharm.sh
alias pycharm='~/.local/share/JetBrains/Toolbox/apps/pycharm/bin/pycharm.sh'
alias guisettings='env XDG_CURRENT_DESKTOP=GNOME gnome-control-center'
# Secrets (tokens / API keys) are NOT in git. They live in ~/.secrets — see tutorcruncher/env.template
[ -f ~/.secrets ] && source ~/.secrets

killport() {
  if [ -z "$1" ]; then
    echo "Usage: killport <port>"
    return 1
  fi

  # Find processes using the port
  pids=$(sudo lsof -t -i:"$1")
  if [ -z "$pids" ]; then
    echo "No process is using port $1."
    return 0
  fi

  echo "Processes using port $1:"
  sudo lsof -i:"$1" | awk 'NR>1 {print "PID: "$2", Command: "$1}'

  count=$(echo "$pids" | wc -l)
  echo "Terminating $count process(es)..."

  echo "$pids" | xargs sudo kill -9

  echo "Done. Killed $count process(es) using port $1."
}

# Time travel function
setdatetime() {
    if [ "$1" = "now" ] || [ "$1" = "reset" ]; then
        echo "Resetting to current time..."
        sudo ntpdate -s time.nist.gov
        echo "Current time: $(date)"
    elif [ "$1" = "tomorrow" ]; then
        echo "Setting date to tomorrow..."
        sudo date -s "tomorrow"
        echo "Current time: $(date)"
    elif [ "$1" = "nextmonth" ]; then
        echo "Setting date to next month..."
        sudo date -s "next month"
        echo "Current time: $(date)"
    elif [ "$1" = "yesterday" ]; then
        echo "Setting date to yesterday..."
        sudo date -s "yesterday"
        echo "Current time: $(date)"
    else
        echo "Setting date to: $1"
        sudo date -s "$1"
        echo "Current time: $(date)"
    fi
}

export PATH="$HOME/repos/TutorCruncher2/env2:$PATH"
# OPENAI_API_KEY is set in ~/.secrets (not committed)

if command -v wt >/dev/null 2>&1; then eval "$(command wt config shell init zsh)"; fi

# sentry
fpath=("$HOME/.local/share/zsh/site-functions" $fpath)

# opencode
export PATH=$HOME/.opencode/bin:$PATH
